name: Docker CI for C++

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rmommM
          password: ${{ secrets.GITHUB-TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/$rmommm/cpp-lab6:${{ github.sha }}

  test:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository_owner }}/cpp-lab6:${{ github.sha }}

      - name: Run tests inside container
        run: docker run --rm ghcr.io/${{ github.repository_owner }}/cpp-lab6:${{ github.sha }}
